---
deployment:
  tasks:
    - export DEPLOYPATH=/home/example/public_html/
    - /bin/cp -R node_modules $DEPLOYPATH
    - export DEPLOYPATH=/home/example/public_html/
    - /bin/cp app.js $DEPLOYPATH
    - /bin/cp controlers.js $DEPLOYPATH
    - /bin/cp package-lock.json $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - /bin/cp README.md $DEPLOYPATH
    - /bin/cp README.txt $DEPLOYPATH
    - /bin/cp routes.js $DEPLOYPATH
    - /bin/cp utils.js $DEPLOYPATH